spring:
  servlet:
    multipart:
      enabled: true #支持文件上传
      file-size-threshold: 0 #支持文件写入磁盘
      location: #上传文件的临时目录
      max-file-size: 10MB #最大支持文件大小
      max-request-size: 10MB #最大支持请求大小