server:
  port: 8081
spring:
  application:
    name: spring-boot-security-thymeleaf
  datasource:
    url: jdbc:mysql://192.168.0.129:3306/test01
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: UTF-8