spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
  data:
    mongodb:
      username: city
      password: 123456
      host: 127.0.0.1
      port: 27017
      database: city