spring:
  application:
    name: spring-boot-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
#    virtual-host: testhost #虚拟主机
    listener:
      simple:
        acknowledge-mode: auto #消息确认
